//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/NewInputActions/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""9fc80815-05d3-487a-96aa-851ef5cec7e7"",
            ""actions"": [
                {
                    ""name"": ""MoveMap"",
                    ""type"": ""Value"",
                    ""id"": ""b8058fd7-08c0-4a5f-af6a-36192dc3bef2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""Scale"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EscButton"",
                    ""type"": ""Button"",
                    ""id"": ""e9242cea-51d0-473e-929f-e4f59e8bdbe7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""84238cf1-239e-4f2b-8b6b-28fc9543c4b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Value"",
                    ""id"": ""adf83df8-f855-4946-98b7-d4da82527d78"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""9dafe8eb-c172-4780-88b1-b062fcce49c6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AddMoney"",
                    ""type"": ""Button"",
                    ""id"": ""2e607fcc-eb2e-4ab7-8636-8b425ebcf471"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubstractMoney"",
                    ""type"": ""Button"",
                    ""id"": ""898aa50f-1c58-4604-a55e-2c388f93bd26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddStatsCat1"",
                    ""type"": ""Button"",
                    ""id"": ""ade773ed-a1d5-4a09-b128-9659919a1821"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddStatsCat2"",
                    ""type"": ""Button"",
                    ""id"": ""12d01490-0942-4323-bbcb-d6ff21e63ad3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddStatsCat3"",
                    ""type"": ""Button"",
                    ""id"": ""231737f8-92a6-4946-ac09-025a4b41574d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Move"",
                    ""id"": ""03bbf844-c201-48c4-9f0f-09cffac2e4b5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f366afae-9304-4292-a27c-d708c32a54c7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""067939b2-3ba2-4347-8b04-3f201dfdd32b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""39f76961-75dc-4e44-88c7-bdb81f2f4b96"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9cfb0a88-f492-4ba0-ac23-31290e3bd2a6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""51d12ba9-1453-4ade-84f3-e3de16864a39"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fd9ddfec-8f3d-45b0-b0cd-f984bda1e7dd"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2e7ad809-fc8b-4da2-8222-79efcf17392a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f65f7c5a-d9d1-45c6-b807-45a5e8f7d81f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7da842d4-7efb-4de9-aaaf-abc1e72f5aaa"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c9fcde66-a7d8-4dc4-9c0f-51f016bb76ea"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0a64e165-554b-43d9-96b2-1d6cd1bf623e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97dbe813-5bea-4034-a905-473bf4137876"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(max=1)"",
                    ""groups"": """",
                    ""action"": ""MoveMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b467f112-9426-4cc1-bbbf-118801fcd01f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d552673f-be7f-49e5-a2f3-9934c98a5553"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3700866-98f1-4e41-9087-5892792e4ac1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7757ca24-e107-4ab3-8c5f-d7ad37741fae"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3126764e-9d10-48ca-9712-f7807e5cb998"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2496ebd1-2770-4290-b4ad-4a8d7590f0f6"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddMoney"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b6dbcd6-c5ed-4437-874d-9d25385c4b6a"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubstractMoney"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f32b360f-3de1-4fb8-9266-3e2c0d12a244"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddStatsCat1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cec3711-f6dc-4056-b1b8-8cfdff4b9400"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddStatsCat2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a927f513-a970-49a8-bc5e-774fae6ba154"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddStatsCat3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MoveMap = m_Player.FindAction("MoveMap", throwIfNotFound: true);
        m_Player_EscButton = m_Player.FindAction("EscButton", throwIfNotFound: true);
        m_Player_MouseClick = m_Player.FindAction("MouseClick", throwIfNotFound: true);
        m_Player_MouseScroll = m_Player.FindAction("MouseScroll", throwIfNotFound: true);
        m_Player_MoveCursor = m_Player.FindAction("MoveCursor", throwIfNotFound: true);
        m_Player_AddMoney = m_Player.FindAction("AddMoney", throwIfNotFound: true);
        m_Player_SubstractMoney = m_Player.FindAction("SubstractMoney", throwIfNotFound: true);
        m_Player_AddStatsCat1 = m_Player.FindAction("AddStatsCat1", throwIfNotFound: true);
        m_Player_AddStatsCat2 = m_Player.FindAction("AddStatsCat2", throwIfNotFound: true);
        m_Player_AddStatsCat3 = m_Player.FindAction("AddStatsCat3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_MoveMap;
    private readonly InputAction m_Player_EscButton;
    private readonly InputAction m_Player_MouseClick;
    private readonly InputAction m_Player_MouseScroll;
    private readonly InputAction m_Player_MoveCursor;
    private readonly InputAction m_Player_AddMoney;
    private readonly InputAction m_Player_SubstractMoney;
    private readonly InputAction m_Player_AddStatsCat1;
    private readonly InputAction m_Player_AddStatsCat2;
    private readonly InputAction m_Player_AddStatsCat3;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveMap => m_Wrapper.m_Player_MoveMap;
        public InputAction @EscButton => m_Wrapper.m_Player_EscButton;
        public InputAction @MouseClick => m_Wrapper.m_Player_MouseClick;
        public InputAction @MouseScroll => m_Wrapper.m_Player_MouseScroll;
        public InputAction @MoveCursor => m_Wrapper.m_Player_MoveCursor;
        public InputAction @AddMoney => m_Wrapper.m_Player_AddMoney;
        public InputAction @SubstractMoney => m_Wrapper.m_Player_SubstractMoney;
        public InputAction @AddStatsCat1 => m_Wrapper.m_Player_AddStatsCat1;
        public InputAction @AddStatsCat2 => m_Wrapper.m_Player_AddStatsCat2;
        public InputAction @AddStatsCat3 => m_Wrapper.m_Player_AddStatsCat3;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @MoveMap.started += instance.OnMoveMap;
            @MoveMap.performed += instance.OnMoveMap;
            @MoveMap.canceled += instance.OnMoveMap;
            @EscButton.started += instance.OnEscButton;
            @EscButton.performed += instance.OnEscButton;
            @EscButton.canceled += instance.OnEscButton;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @MouseScroll.started += instance.OnMouseScroll;
            @MouseScroll.performed += instance.OnMouseScroll;
            @MouseScroll.canceled += instance.OnMouseScroll;
            @MoveCursor.started += instance.OnMoveCursor;
            @MoveCursor.performed += instance.OnMoveCursor;
            @MoveCursor.canceled += instance.OnMoveCursor;
            @AddMoney.started += instance.OnAddMoney;
            @AddMoney.performed += instance.OnAddMoney;
            @AddMoney.canceled += instance.OnAddMoney;
            @SubstractMoney.started += instance.OnSubstractMoney;
            @SubstractMoney.performed += instance.OnSubstractMoney;
            @SubstractMoney.canceled += instance.OnSubstractMoney;
            @AddStatsCat1.started += instance.OnAddStatsCat1;
            @AddStatsCat1.performed += instance.OnAddStatsCat1;
            @AddStatsCat1.canceled += instance.OnAddStatsCat1;
            @AddStatsCat2.started += instance.OnAddStatsCat2;
            @AddStatsCat2.performed += instance.OnAddStatsCat2;
            @AddStatsCat2.canceled += instance.OnAddStatsCat2;
            @AddStatsCat3.started += instance.OnAddStatsCat3;
            @AddStatsCat3.performed += instance.OnAddStatsCat3;
            @AddStatsCat3.canceled += instance.OnAddStatsCat3;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @MoveMap.started -= instance.OnMoveMap;
            @MoveMap.performed -= instance.OnMoveMap;
            @MoveMap.canceled -= instance.OnMoveMap;
            @EscButton.started -= instance.OnEscButton;
            @EscButton.performed -= instance.OnEscButton;
            @EscButton.canceled -= instance.OnEscButton;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @MouseScroll.started -= instance.OnMouseScroll;
            @MouseScroll.performed -= instance.OnMouseScroll;
            @MouseScroll.canceled -= instance.OnMouseScroll;
            @MoveCursor.started -= instance.OnMoveCursor;
            @MoveCursor.performed -= instance.OnMoveCursor;
            @MoveCursor.canceled -= instance.OnMoveCursor;
            @AddMoney.started -= instance.OnAddMoney;
            @AddMoney.performed -= instance.OnAddMoney;
            @AddMoney.canceled -= instance.OnAddMoney;
            @SubstractMoney.started -= instance.OnSubstractMoney;
            @SubstractMoney.performed -= instance.OnSubstractMoney;
            @SubstractMoney.canceled -= instance.OnSubstractMoney;
            @AddStatsCat1.started -= instance.OnAddStatsCat1;
            @AddStatsCat1.performed -= instance.OnAddStatsCat1;
            @AddStatsCat1.canceled -= instance.OnAddStatsCat1;
            @AddStatsCat2.started -= instance.OnAddStatsCat2;
            @AddStatsCat2.performed -= instance.OnAddStatsCat2;
            @AddStatsCat2.canceled -= instance.OnAddStatsCat2;
            @AddStatsCat3.started -= instance.OnAddStatsCat3;
            @AddStatsCat3.performed -= instance.OnAddStatsCat3;
            @AddStatsCat3.canceled -= instance.OnAddStatsCat3;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMoveMap(InputAction.CallbackContext context);
        void OnEscButton(InputAction.CallbackContext context);
        void OnMouseClick(InputAction.CallbackContext context);
        void OnMouseScroll(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnAddMoney(InputAction.CallbackContext context);
        void OnSubstractMoney(InputAction.CallbackContext context);
        void OnAddStatsCat1(InputAction.CallbackContext context);
        void OnAddStatsCat2(InputAction.CallbackContext context);
        void OnAddStatsCat3(InputAction.CallbackContext context);
    }
}
